### ISSUE TITLE
Build-Task Create should maintain dependencies 

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr#100] opened 2018-05-18 21:44 UTC
Repro steps

1. Create a build-task based on an image from the same registry

```sh
az acr build-task create \
  -n demo42web \
  --context https://github.com/demo42/web \
  -t demo42/web:{{.Build.ID}} \
  --cpu 2 \
  --branch $BRANCH \
  -f ./src/WebUI/Dockerfile \
  --build-arg REGISTRY_NAME=$REGISTRY_NAME \
  --git-access-token $(az keyvault secret show \
                         --vault-name $AKV_NAME \
                         --name $GIT_TOKEN_NAME \
                         --query value -o tsv) \
  --registry $ACR_NAME 
```

1. Run the build task `az acr build-task run -n demo42web`
1. Update the base image: https://github.com/demo42/baseimage-aspnetcoreruntime/blob/master/Dockerfile
1. `watch -n1 az acr build-task list-builds`
1. Notice the image is rebuilt
1. Update the build task, with the `update` sub-command

```sh
az acr build-task update\
  -n demo42web \
  --context https://github.com/demo42/web \
  -t demo42/web:{{.Build.ID}} \
  --cpu 2 \
  --branch $BRANCH \
  -f ./src/WebUI/Dockerfile \
  --build-arg REGISTRY_NAME=$REGISTRY_NAME \
  --git-access-token $(az keyvault secret show \
                         --vault-name $AKV_NAME \
                         --name $GIT_TOKEN_NAME \
                         --query value -o tsv) \
  --registry $ACR_NAME 
```
Dependencies are maintained
```sh
"baseImageDependencies": [
      {
        "additionalProperties": {},
        "digest": "sha256:0de62e0f39a92b274e48a1e475b46656b4e5283c5392870d06809ed507808b5f",
        "registry": "jengademos.azurecr.io",
        "repository": "baseimages/microsoft/aspnetcore-runtime",
        "tag": "linux-2.1",
        "type": "Runtime"
      }
```

Use `create` for Desired State Configuration
```sh
az acr build-task create \
  -n demo42web \
  --context https://github.com/demo42/web \
  -t demo42/web:{{.Build.ID}} \
  --cpu 2 \
  --branch $BRANCH \
  -f ./src/WebUI/Dockerfile \
  --build-arg REGISTRY_NAME=$REGISTRY_NAME \
  --git-access-token $(az keyvault secret show \
                         --vault-name $AKV_NAME \
                         --name $GIT_TOKEN_NAME \
                         --query value -o tsv) \
  --registry $ACR_NAME 
```
and the dependencies are nulled
```sh
"baseImageDependencies": null,
```

For more commands
https://github.com/demo42/deploy/blob/master/create/acr-build.md

**Comment by sajayantony** [comment] 2018-08-02 20:26
@mnltejaswini  - Can we close this now?

**Comment by sajayantony** [comment] 2018-09-01 00:50
Create is not recommended since it will PUT to what ever properties are provided and is the expected behavior by design.

**Closed by sajayantony** 2018-09-01 00:50 UTC
Labels: bug, build
