### ISSUE TITLE
az acr import sits in Running state

### ISSUE THREAD

**Issue by gtam** [Azure/acr#549] opened 2021-06-02 21:40 UTC
**Describe the bug**
Running the import job against a GCP Artifact Registry with service account keys described here https://cloud.google.com/artifact-registry/docs/docker/authentication#json-key.  The password pass into the command is base64 encoded password (~4000 characters long).  The import job remains in Running state.  Appending --debug repeats a HTTP 202 status message indicating the import job has been accepted. 

Scrubbed Log:
.http_logger: Response status: 202
.http_logger: Response headers:
.http_logger:     'Cache-Control': 'no-cache'
.http_logger:     'Pragma': 'no-cache'
.http_logger:     'Content-Length': '67'
.http_logger:     'Content-Type': 'application/json; charset=utf-8'
.http_logger:     'Expires': '-1'
.http_logger:     'Location': 'https://management.azure.com/subscriptions/<SCRUBBED>/providers/Microsoft.ContainerRegistry/locations/WESTUS/operationResults/<SCRUBBED>?api-version=2020-11-01-preview'
.http_logger:     'Retry-After': '10'
.http_logger:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
.http_logger:     'Server': 'Microsoft-HTTPAPI/2.0'
.http_logger:     'x-ms-ratelimit-remaining-subscription-reads': '<SCRUBBED>'
.http_logger:     'x-ms-request-id': '<SCRUBBED>'
.http_logger:     'x-ms-correlation-request-id': '<SCRUBBED>'
.http_logger:     'x-ms-routing-request-id': '<SCRUBBED>'
.http_logger:     'X-Content-Type-Options': 'nosniff'
.http_logger:     'Date': 'Sat, 29 May 2021 13:33:02 GMT'
.http_logger: Response content:
.http_logger: {"registry/repo:tag":"Pending","status":"Accepted"}

**To Reproduce**
1. Attempt an import from GCR using a service account and a base64 encoded password ~4000 characters long.
IE: az acr import -n $registry --source $sourceImage:$tag --user $user --password $pass --image $targetImage:$tag

**Expected behavior**
The import should succeed or some timeout with a useful error to indicate reason for failure.

**Screenshots**
N/A

**Any relevant environment information**
 - OS: [e.g. Ubuntu, Windows]: MacOS/Windows
 - Azure CLI/PowerShell/SDK version: 2.21.0
 - Docker version: N/A
 - Datetime (UTC) when the issue occurred: N/A
 - Registry and image names: N/A

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by northtyphoon** [comment] 2021-06-03 00:51
@gtam, it looks the issue is the source registry you tried to import image from didn't support Range headers in HTTP requests.

**Comment by dominik-lekse** [comment] 2021-07-01 15:36
The documentation of GCP Artifact Registry tells "Artifact Registry does not support Docker chunked uploads. Some container image tools support uploading large container images with either chunked uploads or a single monolithic upload. You must use monolithic uploads when you push container images to Artifact Registry." (https://cloud.google.com/artifact-registry/docs/reference/docker-api). Beyond, there is no comment in the docs about chunked blob downloads.

When debugging the HTTP traffic, I also observed that GCP AR does not announce Range headers in HEAD requests on `/v2/<name>/blobs/<digest>`.

Lets assume that
- range headers will not be supported by GCP Artifact Registry in the near future *and*
- we want improve interoperability between Azure and GCP *and*
- we want to make it easier for customers to migrate container registries from GCP to Azure

Then, it would be helpful if ACR import would support importing images from Docker registries which do not support Range headers or chunked blob requests.

I guess the assumption is valid, that *in theory* the absence of support for Range headers is not blocking importing the image.

**Comment by shizhMSFT** [comment] 2021-08-06 07:11
Thanks for bringing this up to our attention.  Due to security concerns, this is a scenario we currently do not support since we rely on range headers.  Our team will discuss and investigate how can we improve Azure interoperability story with GCP in a way that is reliable and secure.

**Comment by sajayantony** [comment] 2021-12-21 19:34
Closing this since there is no plan to fix this at this point.

**Closed by sajayantony** 2021-12-21 19:34 UTC
Labels: bug, wontfix
