### ISSUE TITLE
"unauthorized: authentication required" which is actually authorized

### ISSUE THREAD

**Issue by doggy8088** [Azure/acr#359] opened 2020-03-17 17:07 UTC
**Describe the bug**
I found this issue when I'm using AKS with ACR. When I pulling image from AKS, it shows `unauthorized: authentication required` which is so misleading.

**To Reproduce**
1. `docker login name.azurecr.io`
2. `docker pull name.azurecr.io:443/repo:notexist`

**Expected behavior**
Show proper error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/88981/76881661-71bf8400-68b4-11ea-8527-5166a16b0a36.png)

**Any relevant environment information**
 - OS: [e.g. Ubuntu, Windows] `Windows` and `Ubuntu`
 - Azure CLI/PowerShell/SDK version: `Azure-cli 2.1.0`
 - Docker version: `19.03.5`
 - Datetime (UTC) when the issue occurred: `2020/03/18`
 - Registry and image names: `appfork8s.azurecr.io:443/appfork8s:123` (not exist tag)

**Additional context**

See also: https://github.com/Azure/AKS/issues/1510

**Comment by doubletr** [comment] 2020-03-18 09:13
I have the same issue. Why it throw Authentication required If we use a wrong repository name or tag?

**Comment by sajayantony** [comment] 2020-03-18 20:08
@shizhMSFT can we check if we follow the conformance test outputs when repo doesn’t exist.

**Comment by adewaleo** [comment] 2020-03-18 22:41
This is strange, someone raised this issue internally and at first I couldn't reproduce this issue with basic or token auth locally. But I notice we are using 443 port. So I could reproduce the issue.

```
> docker pull testbrsreg.azurecr.io/hello-world2:latest        Error response from daemon: manifest for testbrsreg.azurecr.io/hello-world2:latest not found: manifest unknown: manifest unknown
> docker pull testbrsreg.azurecr.io:443/hello-world2:latest    Error response from daemon: Get https://testbrsreg.azurecr.io:443/v2/hello-world2/manifests/latest: unauthorized: authentication required
```
```
> docker login testbrsreg.azurecr.io:443 -u testbrsreg -p $password
> docker pull testbrsreg.azurecr.io:443/hello-world2:latest
Error response from daemon: manifest for testbrsreg.azurecr.io:443/hello-world2:latest not found: manifest unknown: manifest unknown
```

Seems like the solution is to make sure to login to the registry with the port number 443 (CLI does not currently support this).

This seems like a docker client issue / design decision... although can update docs and make slight changes to az acr login (try logging in to 443 as well) to help improve user experience

**Comment by sajayantony** [comment] 2020-03-18 22:47
Ok I just went back and read this. You cannot use different host:port combination for login and pull. The name is fully case sensitive as well. This is as per docker client behavior.

**Comment by yugangw-msft** [comment] 2020-04-21 18:00
Closing

**Closed by yugangw-msft** 2020-04-21 18:00 UTC
Labels: bug

**Comment by doggy8088** [comment] 2020-04-22 02:44
@sajayantony What do you mean `You cannot use different host:port combination for login and pull.`?  Does the solution from @adewaleo is the recommended way to solve this issue?

@yugangw-msft Are you going to update docs about this issue? Will this issue keep tracking until docs been updated?

**Comment by adewaleo** [comment] 2020-04-22 18:39
@doggy8088 you are currently doing the following:

docker login appfork8s.azurecr.io

docker pull appfork8s.azurecr.io:**443**/appfork8s:123

This is not allowed.

You must either do (the docker client supports):

```
docker login appfork8s.azurecr.io

docker pull appfork8s.azurecr.io/appfork8s:123
```

or 

```
docker login appfork8s.azurecr.io:443

docker pull appfork8s.azurecr.io:443/appfork8s:123
```
