### ISSUE TITLE
docker pull failed by "unauthorized"

### ISSUE THREAD

**Issue by tanaka-takayoshi** [Azure/acr#54] opened 2017-08-02 00:48 UTC
Though I could log in and push an image to ACR repository, I failed to pull the same image.

```
$ sudo docker push example.azurecr.io/nginx:latest
The push refers to a repository [example.azurecr.io/nginx]
af5bd3938f60: Pushed 
29f11c413898: Pushed 
eb78099fbf7f: Pushed 
latest: digest: sha256:788fa27763db6d69ad3444e8ba72f947df9e7e163bad7c1f5614f8fd27a311c3 size: 948

$ sudo docker pull example.azurecr.io/nginx:latest
Trying to pull repository example.azurecr.io/nginx ... 
unauthorized: authentication required
```

I wonder my docker version is 1.12, which is the stable latest version at Fedora 25.

```
$ sudo docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-7.gitae7d637.fc25.x86_64
 Go version:      go1.7.6
 Git commit:      ae7d637/1.12.6
 Built:           Tue Jul 18 16:18:12 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-7.gitae7d637.fc25.x86_64
 Go version:      go1.7.6
 Git commit:      ae7d637/1.12.6
 Built:           Tue Jul 18 16:18:12 2017
 OS/Arch:         linux/amd64
```

Is there any limitation of docker version?

**Comment by tanaka-takayoshi** [comment] 2017-08-02 03:25
I found docker 17.06.0-ce on RHEL 7.3 can pull an image from the same registry. Could you add the version requirement in the document?

```
# docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

# docker pull takayoshi733.azurecr.io/nginx:latest
latest: Pulling from nginx
94ed0c431eb5: Pull complete 
9406c100a1c3: Pull complete 
aa74daafd50c: Pull complete 
Digest: sha256:788fa27763db6d69ad3444e8ba72f947df9e7e163bad7c1f5614f8fd27a311c3
Status: Downloaded newer image for takayoshi733.azurecr.io/nginx:latest
```

**Comment by SajayAntony** [comment] 2017-08-02 07:23
@tanaka-takayoshi Thanks for bringing this to our attention. We will make a note to call this out. 
@SteveLas  - Do we document what is the supported docker tooling version in VS and other areas. It think ACR should also use the same min version requirement. 
/cc @yuwaMSFT2

**Comment by yuwaMSFT2** [comment] 2017-08-02 17:36
I have been using some older version 1.11.2 and 1.12.1 on Ubuntu and they worked fine. The error means that for docker push it picked up the correctly cached user:pwd pair for the registry example.azurecr.io from the config.json file, but for docker pull it didn't find matching cache entry for the same registry. It is strange and it should not be specific to Acr. I don't have Fedora so not sure.

Are you sure you are using the exactly same registry (example.azurecr.io)? Can you pull/push from docker hub or other registry?

**Comment by tanaka-takayoshi** [comment] 2017-08-02 23:54
@YuanMSFT I use exactly same registry URL for pushing and pulling. Also, I can push and pull another private docker repository. Only Azure Container Registry fails to pull.

**Comment by drajen** [comment] 2017-08-15 15:13
I can confirm this issue with Red Hat OpenShift 3.5 on RHEL 7.4 which uses Docker 1.12.6.

**Comment by ankurkhemani** [comment] 2017-08-16 00:00
@drajen @tanaka-takayoshi  I am able to push/pull images to ACR, running Docker 1.12.6 on RHEL 7.4, Here's a screenshot.

![image](https://user-images.githubusercontent.com/1878124/29341713-004b8a98-81db-11e7-9262-bc493d0a3833.png)

**Comment by drajen** [comment] 2017-08-17 00:00
In my particular case with OpenShift 3.5 and Docker 1.12.6 from Red Hat I had to add `--signature-verification=false` to `OPTIONS` in `/etc/sysconfig/docker` and restart docker with `systemctl restart docker`. `docker pull` from ACR now works as intended. I want to caveat this with that I have no clue what side effects this might have on OpenShift.

**Comment by tanaka-takayoshi** [comment] 2017-08-17 07:53
Thanks @drajen . I confirmed ``--signature-verification=false`` is required with Docker 1.12.6 on RHEL 7.3. I confirmed the RHEL 7.3 on Azure. It seemed Red Hat provided Docker issue.

**Comment by SajayAntony** [comment] 2017-08-29 23:27
Close this for now and can open if we see this again.

**Closed by SajayAntony** 2017-08-29 23:27 UTC
