### ISSUE TITLE
On-premise registry support, as a geo-replicated node.

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr#419] opened 2020-06-23 17:26 UTC
To support on-premise workloads that support bi-directional replication to/from azure.
This will support connected nodes, occassionally connected nodes and air-gapped nodes for IoT [Purdue Network isolated environments](https://en.wikipedia.org/wiki/Purdue_Enterprise_Reference_Architecture).

**Comment by toddysm** [comment] 2021-01-28 02:21
Duplicate of #493

**Closed by toddysm** 2021-01-28 02:21 UTC
Labels: feature-request
