### ISSUE TITLE
Image signature is not visible when image is imported from one acr to other acr

### ISSUE THREAD

**Issue by akshay-mahakalkar** [Azure/acr#496] opened 2020-12-02 11:17 UTC
**Issue Description**
I have signed image in Azure Container Registry (ACR) with Docker Content Trust (DCT). Images are getting signed properly. But when images are imported from one ACR to another ACR image signature is not visible.
I am importing images with az acr import command
Is this an expected behavior?
Is there any workaround to preserve image signature when moved from one ACR to other?

**To Reproduce**
1. Create a docker image or import any image from public repository
2. Tag image with docker tag <downloadedImage>:<tag> <acrURL>/<downloadedImage>:<tag>
3. Sign image with DCT. Check here, https://docs.docker.com/engine/security/trust/#signing-images-with-docker-content-trust
4. Push image to ACR if not.
5. Verify the signature using docker trust inspect. check here, https://docs.docker.com/engine/reference/commandline/trust_inspect
6. Signature is visible.
7. Use az ACR import command to import signed image from one ACR to other.
8. Download image from destination ACR using docker pull command. 
9. Again verify the signature using docker trust inspect. check here, https://docs.docker.com/engine/reference/commandline/trust_inspect 
10. Signature is not visible

**Expected behavior**
Output of step 5 and step 10 should be same.

**Comment by aviral26** [comment] 2020-12-02 12:05
This is a known limitation of the current Docker Content Trust implementation and there is an ongoing effort to address this and other concerns around signatures with Notary V2. More information here: https://github.com/notaryproject/requirements
cc @shizhMSFT , @SteveLas , @sajayantony

**Comment by akshay-mahakalkar** [comment] 2020-12-02 12:37
Hi @aviral26 ,

Thanks for the update. It would be great if you could please suggest an alternative way of maintaining the trust of images between ACR's in production environments.

**Comment by SteveLasker** [comment] 2020-12-02 20:15
Hi @akshay-mahakalkar, the core problem is there is no really viable solution. There are some various efforts from [Palo Alto Networks Prisma Cloud](https://www.paloaltonetworks.com/prisma/cloud), [docker-lock](https://github.com/safe-waters/docker-lock) and I just heard of [connaisseur](https://github.com/sse-secure-systems/connaisseur). But, none of them really solve the problem as the e2e stack must evolve.
This is the reason we're pressing forward for Notary V2 as @aviral26 noted above.

**Comment by SteveLasker** [comment] 2020-12-09 00:30
Closing this issue as this is "by design" as we move to a more complete solution with Notary v2. 
To get a sense of where ACR is going with Notary v2, here's a mock of the experience we're shooting for. Below, you can see ACR supports multiple artifact types. You'll then be able to see what the artifact type is, if it's signed, if it has meta-data, and possibly an SBOM.
![image](https://user-images.githubusercontent.com/7647382/101557758-7bbd7180-3972-11eb-8972-51dec1302161.png)

**Closed by SteveLasker** 2020-12-09 00:30 UTC
Labels: bug
