### ISSUE TITLE
Creating ACR registry: throws error Error creating ACR. Please try again later. Response from az was not json: b''.

### ISSUE THREAD

**Issue by jazzz308** [Azure/acr#37] opened 2017-04-06 02:26 UTC
I am trying to create aml environment using DSVM.  and when I run **aml env setup** I get the following error....

Subscription set to Azure Pass
Continue with this subscription (Y/n)? y
Resource group devmlrg already exists, skipping creation.
Registering is still on-going. You can monitor using 'az provider show -n Microsoft.Storage'
Creating storage account devmlstor.
Registering is still on-going. You can monitor using 'az provider show -n Microsoft.ContainerRegistry'
Creating ACR registry: devmlacr (please be patient, this can take several minutes)
Error creating ACR. Please try again later. Response from az was not json: b''.

Any suggestions that would help to resolve the issue??

Thanks

**Comment by SajayAntony** [comment] 2017-04-06 03:52
Can you please try registering the provider as per https://github.com/Azure/acr/blob/master/docs/Troubleshooting%20Guide.md

**Comment by djyou** [comment] 2017-04-06 04:11
Hi jazzz308,

Error messages in [Azure CLI](https://github.com/Azure/azure-cli) are not always json, this could be by design as error messages are meant to be parsed and read by a human. It looks like you are using [AMLBD CLI](https://github.com/Azure/amlbdcli) to create storage account and registry, which however doesn't handle non-json error messages.

I am not seeing any logs to our server side with the registry name `devmlacr` so I suspect it is a client side error. If you don't have access to the above repo, I can help you raise an issue so that registry creation can be properly handled.

**Comment by jazzz308** [comment] 2017-04-06 05:42
Hi djyou,

I have re-tried with different group **devmlcntkacr** and got the same result.  Do you see any logs relating to that?  What sort of logs do i need to see from the client side?

**Comment by djyou** [comment] 2017-04-06 15:59
I have raised an issue against the module you were using and I will keep you posted.

I wasn't sure if you can see any logs but some error messages of why the operation failed will be very helpful. Also I can see that you were creating resources in `East US`, can you share your region?

**Comment by jazzz308** [comment] 2017-04-06 22:59
Thanks for raising the issue.  

My region is Korea Central but when I run I run **aml env setup** from putty it somehow installs storage account in US East and throws that error at the end.  Do you think because of the different region it is trying to install ACR?

**Comment by djyou** [comment] 2017-04-21 21:12
Hi jazzz308,

Are you still having the problem? The ML team acknowledged that they have been working on the fix to the issue. One quick way to mitigate the issue is to create the resource group/storage account/container registry in the same region and also have your VM deployed in the same region (or close). I wasn't sure if they are configurable from the module you were using but it is worth trying.

**Comment by djyou** [comment] 2017-04-24 22:09
Closed as this issue has been transferred to amlbdcli team.

**Closed by djyou** 2017-04-24 22:09 UTC
Labels: bug
